# name of the software
name: HQ Trivia Discord Bot

project:
    version: 0.1.0
    add_url: https://discordapp.com/oauth2/authorize?client_id=463127758143225874&permissions=18432&scope=bot

links:
    header:
      - title: Online Stats
        url: https://stats.hqtrivia.pro
      - title: GitHub
        url: https://github.com/Chewsterchew/HQ-DiscordBot
      - title: Support Server
        url: https://discord.gg/Wr2yawT
    footer:
      - title: GitHub
        url: https://github.com/Chewsterchew/HQ-DiscordBot
      - title: Issues
        url: https://github.com/Chewsterchew/HQ-DiscordBot/issues?state=open

ui:
    header:
        color1: "#080331"
        color2: "#673051"
        trianglify: true

social:
    github:
        user: Chewsterchew
        repo: HQ-DiscordBot
    twitter:
        enabled: false
        via:
        hash:
        account:
    facebook:
        enabled: false
        profileUrl:

analytics:
    google:

# Build settings
markdown: kramdown
exclude:
    - Gemfile
    - Gemfile.lock
